name: proto_hair
description: "Prototype aplikasi pewarnaan rambut berbasis AR menggunakan Flutter."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lucide_flutter: 0.548.0
  uuid: ^4.4.0
  intl: ^0.19.0
  camera: ^0.11.1+1 
  permission_handler: ^11.3.1
  tflite_flutter: ^0.12.1
  image: ^4.2.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/